apiVersion: apps/v1
kind: Deployment
metadata:
  name: msc-registry-server-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msc-registry-server
  template:
    metadata:
      labels:
        app: msc-registry-server
    spec:
      containers:
        - name: msc-registry-server
          image: vifa951002/msc-registry-server
          ports:
            - containerPort: 8761
