apiVersion: v1
kind: Service
metadata:
  name: msc-registry-server
spec:
  selector:
    app: msc-registry-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761