apiVersion: v1
kind: Service
metadata:
  name: msc-registry-server
spec:
  selector:
    app: msc-registry-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      name: registry-server